apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: secret/data/keycloak
        property: KEYCLOAK_ADMIN
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/keycloak
        property: KEYCLOAK_ADMIN_PASSWORD