package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/example/shipping/internal/graph/model"
)

// FindCarrierByID resolves a Carrier entity by ID for federation.
// Catalog (and other services) extend Carrier — Apollo Router calls this
// to resolve carrier data when stitching cross-service queries.
func (r *entityResolver) FindCarrierByID(ctx context.Context, id string) (*model.Carrier, error) {
	carrier, ok := carriers[id]
	if !ok {
		return nil, fmt.Errorf("carrier %q not found", id)
	}
	return carrier, nil
}

// FindProductByID is called by Apollo Router to resolve the Product entity.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	return &model.Product{
		ID: id,
		ShippingInfo: &model.ShippingInfo{
			Carrier: carriers["fedex"],
		},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
