package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/example/shipping/internal/graph/model"
)

// Shipping returns ShippingInfo for a product.
func (r *queryResolver) Shipping(ctx context.Context, productID string) (*model.ShippingInfo, error) {
	return &model.ShippingInfo{
		Carrier: carriers["fedex"],
	}, nil
}

// Carriers returns all known carriers.
func (r *queryResolver) Carriers(ctx context.Context) ([]*model.Carrier, error) {
	result := make([]*model.Carrier, 0, len(carriers))
	for _, c := range carriers {
		result = append(result, c)
	}
	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
