package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"github.com/example/shipping/internal/graph/model"
)

// Shipping is the resolver for the shipping field.
func (r *queryResolver) Shipping(ctx context.Context, productID string) (*model.ShippingInfo, error) {
  return &model.ShippingInfo{
      ID:            "ship-1",
      ProductID:     productID,
      EstimatedDays: 3,
      Carrier:       "FedEx",
  }, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
