// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type ShippingInfo struct {
	ID            string `json:"id"`
	ProductID     string `json:"productId"`
	EstimatedDays int    `json:"estimatedDays"`
	Carrier       string `json:"carrier"`
}
