// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Carrier struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	EstimatedDays int    `json:"estimatedDays"`
}

func (Carrier) IsEntity() {}

type Product struct {
	ID           string        `json:"id"`
	ShippingInfo *ShippingInfo `json:"shippingInfo"`
}

func (Product) IsEntity() {}

type Query struct {
}

type ShippingInfo struct {
	Carrier *Carrier `json:"carrier"`
}
