image:
  repository: localhost:5000/catalog
  tag: sha-ded8841

containerPort: 4001

service:
  port: 4001

health:
  path: /actuator/health

istio:
  destinationRule:
     enabled: true
  virtualService:
    enabled: false
  authorizationPolicy:
    enabled: false
    allowFrom:
      - namespace: default
        serviceAccount: apollo-router
  peerAuthentication:
    enabled: false
    mode: STRICT
