image:
  repository: localhost:5000/catalog
  tag: sha-33331da

containerPort: 4001

service:
  port: 4001

health:
  path: /actuator/health

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  allowFrom:
    - app: apollo-router
      ports: [ 4001 ]

istio:
  destinationRule:
    enabled: true

  virtualService:
    enabled: true

  requestAuthentication:
    enabled: false
    jwtRules:
      - issuer: "https://idp-server.com"
        jwksUri: "https://your-idp.com/.well-known/jwks.json"
  authorizationPolicy:
    enabled: true
    allowFrom:
      - namespace: default
        serviceAccount: apollo-router
  #        requiredScopes:
  #          - "catalog:read"

  peerAuthentication:
    enabled: true
    mode: STRICT
